name: webapp_template
description: Sample plugin that serves a web app UI using websocket
version: "1.0"
author: diginatu
method: std
exec:
nagomever: ""
depends:
- nagome
- nagome_ui
- nagome_comment
