name: Upload Release Asset

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2 with:
          go-version: 1.16

      - name: Build
        run: |
          go install github.com/mitchellh/gox
          make cross

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/nagome-webapp-server_linux_amd64
            release/nagome-webapp-server_windows_amd64.exe
            release/nagome-webapp-server_darwin_amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
